[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## Unity C\#热重载

### 关键接口

####  UnityEditor\.Compilation\.CompilationPipeline<br/>\.GetAssemblyNameFromScriptPath\(filePath\) <br/>可通过脚本路径获取程序集名称

### 实现仓库
- LINK
<pre>https://github.com/Misaka-Mikoto-Tech/UnityScriptHotReload</pre>
