[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## ET

### github
- LINK
<pre>https://github.com/egametang/ET</pre>

### 状态同步

### 6\.0的运行
- LINK
<pre>https://blog.csdn.net/Super_killer_lx/article/details/125717645</pre>
