[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## HybridCLR

### 知乎专栏
- LINK
<pre>https://www.zhihu.com/column/c_1489549396035870720</pre>

### GitHub
- LINK
<pre>https://github.com/focus-creative-games/hybridclr/blob/main/README_zh.md</pre>

### 热更新原理

#### 拓展了IL2CPP VM的服务

#### 在使用“原来的数据内存对象”的情况下，<br/>拓展了解析执行IL代码的能力

#### 让IL2CPP的运行模式变成三个部分：

##### 数据内存对象

##### AOT代码机器指令

##### Interpreter IL指令解析执行

###### HybridCLR不仅支持传统的全解释执行模式，还开创性地实现了 Differential Hybrid Execution\(DHE\)<br/> 差分混合执行技术。即可以对AOT dll任意增删改，会智能地让变化或者新增的类和函数以interpreter模式运行，<br/>但未改动的类和函数以AOT方式运行，让热更新的游戏逻辑的运行性能基本达到原生AOT的水平。
