[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 渲染与优化浅析

### 渲染管线基本介绍

#### Shader

##### 怎么调试

###### 把值输出为颜色

###### FrameDebugger

###### RenderDoc

### 渲染相关性能优化

#### 什么是drawcall

##### 为什么drawcall会耗

##### dc越少就越不卡？

#### Spine优化

#### UGUI优化

#### 定位的工具的手法
