[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## Shader接口

### 顶点变换接口

#### UnityObjectToClipPos

##### 本地坐标直接转成clip space的空间

##### equivalent of mul\(UNITY\_MATRIX\_MVP, float4\(pos, 1\.0\)\),

#### UnityObjectToViewPos

##### equivalent of mul\(UNITY\_MATRIX\_MV, float4\(pos, 1\.0\)\)\.xyz
