[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 帧同步

### 英文叫LockStep?

#### 为了让运行结果不与硬件速度关联，所以不能用Time\.deltaTime来作为差值<br/>更新，而是用固定的时间片段作为阈值，所以这里的Lock也就是Fixed的意思？

### 定义

#### 这里的帧同步，并不是每帧都进行同步的意思

#### 而是按照相同的间隔执行逻辑

#### 在某一帧如果发生了特殊的事情，就把事件记录下来<br/>战斗结束的时候把列表发给后端

### 参考项目
- LINK
<pre>https://github.com/passiony/LockStep</pre>

### 参考教程

#### 渔夫
- LINK
<pre>https://github.com/JiepengTan/Lockstep-Tutorial</pre>

##### 执行流程

###### GameManager

####### 判断是否在回放

######## 请求Msg\_JoinRoom

######## 回放流程

######### 反序列化回放文件数据到GameManager

######### StartGame

### 使用场景

#### 多人试试对战

#### 需要战斗回放功能的

#### 需要加速功能的

#### 需要服务器同步校验防作弊

### 如何实现可行的帧同步

#### 可靠稳定的同步基础算法

#### 消除浮点数带来的精度误差

##### 定点数

###### 小数点的位置是固定的还是浮动的

###### 项目内增加了一个Fix64的数据类型来封装

####### 封装的底层是long

#### 控制好随机数

##### 随机数

### 帧同步原理

#### 渲染更新机制

##### 不能直接操作transform的属性，而是用上一个位置和当前帧的位置就行插值

### 帧同步类型

#### 常规帧同步

##### 也就是前端把输入发给服务器之后，不做本地处理，<br/>只有服务器广播的时候才执行

##### 预测回滚的帧同步

###### 发给服务器之后，前端做输入预测，服务器下发的时候如果跟预测的不一样<br/>就对世界状态进行回滚到服务器下发的开始帧，再演算一遍

### 怎么debug

#### 1 把世界状态序列化，dump到文件

#### 2\.记录事件列表，到文件

#### 3\.拿两个客户端的上面的两个文件对比，就知道哪里不一致了
