[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## Shader教程

### Freya Holmer
- LINK
<pre>https://www.youtube.com/watch?v=kfM-yu0iQBk&amp;list=PLImQaTpSAdsCnJon-Eir92SZMl7tPBS4Z</pre>

#### frac

##### 本质上是取小数点，但是也可以用来看数是否超过1了，如果超过了<br/>就会有一定的重复模式

### 个人作品展示网站

#### Art\-station
- LINK
<pre>https://www.artstation.com/about</pre>

## 渲染相关

### 一些好的链接

#### LOL的渲染技术
- LINK
<pre>https://zhuanlan.zhihu.com/p/270560224</pre>

#### 谈一谈英雄联盟手游渲染2——高级篇
- LINK
<pre>https://zhuanlan.zhihu.com/p/286836840</pre>

## 可视化公式的变化曲线

### desmos
- LINK
<pre>https://www.desmos.com/calculator</pre>
