[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## Shader教程

### Freya Holmer
- LINK
<pre>https://www.youtube.com/watch?v=kfM-yu0iQBk&amp;list=PLImQaTpSAdsCnJon-Eir92SZMl7tPBS4Z</pre>

### 个人作品展示网站

#### Art\-station
- LINK
<pre>https://www.artstation.com/about</pre>

## 渲染相关

### 一些好的链接

#### LOL的渲染技术
- LINK
<pre>https://zhuanlan.zhihu.com/p/270560224</pre>

#### 谈一谈英雄联盟手游渲染2——高级篇
- LINK
<pre>https://zhuanlan.zhihu.com/p/286836840</pre>
