[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## VO

### Velocity Obstacle

#### 经典形态 RVO

##### Receprocal Velocity Obstacle

##### 最大的改进就是假设对方也会使用和我们相同的策略，而非保持匀速移动

#### ORCA 究极进化

##### Optimal Reciprocal Collision Avoiddance

##### 解决多物体之间的避障问题

##### 在多条先组成的多边形区域内找到最优解

###### 高中数学的线性规划问题

##### 无解的时候后退避障

#### https://gamma\.cs\.unc\.edu/RVO2/
- LINK
<pre>https://gamma.cs.unc.edu/RVO2/</pre>

#### 论文
- LINK
<pre>https://gamma.cs.unc.edu/ORCA/publications/ORCA.pdf</pre>

#### 参考unity代码
- LINK
<pre>https://github.com/warmtrue/RVO2-Unity</pre>

#### B站参考
- LINK
<pre>https://www.bilibili.com/video/BV1Nb421n7qJ/?spm_id_from=333.999.0.0&amp;vd_source=72868cdf66be986462ce798fe9e21050</pre>

#### 思路

##### 找出速度VO并判断相对读物是否会落在碰撞域内

##### 找出让速度向量V离开碰胡子那个域的最小附加速度向量u

#### C\+\+仓库

## CleanPath
> leftSide=`true`


### YouTube
- LINK
<pre>https://www.youtube.com/watch?v=Hc6kng5A8lQ&amp;list=PLD56A0C7765234DCD&amp;index=13&amp;ab_channel=GAMMAUMD</pre>

### 文档
- LINK
<pre>https://gamma.cs.unc.edu/CA/</pre>

## KD\-Tree
> leftSide=`true`


### 用来查询最近点的数据结构
- LINK
<pre>https://www.youtube.com/watch?v=BK5x7IUTIyU&amp;ab_channel=Computerphile</pre>

### K代表的是多少维，D是demension

### KD树是什么

#### 表示k维点的二叉树结构

#### 每个非叶子节点作为一个超平面（hyperplane\),把空间划分为两部分

#### 构建过程

##### 当本地agent数量和Simulator的agent数量不一样的时候创建新的<br/>AgentTree节点的数量是agent数量的两倍

##### 从第一个agent递归的构建树

###### 先遍历begin到end的agent找出所有agent的XY轴的最大最小值

###### 根据两个轴的区间范围的距离来决定要水平分割还是竖直分割<br/>代码例子是用区间小的

###### 用选择区间的计算出中间的分割值

###### 当left比right小的时候，一直迭代
> leftSide=`true`


####### 左边agent值比分界的小的话，left\+1

####### 右边agent值比分界值大的话，right\-1
> leftSide=`true`


####### 当left\<right的时候，交换对应agent位置

###### 继续递归构建左树和右树
> leftSide=`true`


#### KDTreeWiki
- LINK
<pre>https://en.wikipedia.org/wiki/K-d_tree</pre>

## FlowField
- LINK
<pre>https://www.youtube.com/watch?v=tSe6ZqDKB0Y&amp;ab_channel=TurboMakesGames</pre>

### 本质上是一个向量场，给定一个目标点，在当前的格子<br/>标出来要向哪个方向走才能走到目标

### 跟A星的区别

#### A星每个单位都要单独计算一次

#### FlowField只要算一次，就能知道在各个位置的走向<br/>每个单位在当前的位置查询表就知道下一步要走到哪里

### links

#### Flow Field Pathfinding for Tower Defense
- LINK
<pre>https://www.redblobgames.com/pathfinding/tower-defense/</pre>
