[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## VO

### Velocity Obstacle

#### 经典形态 RVO

##### Receprocal Velocity Obstacle

##### 最大的改进就是假设对方也会使用和我们相同的策略，而非保持匀速移动

#### ORCA 究极进化

##### Optimal Reciprocal Collision Avoiddance

#### https://gamma\.cs\.unc\.edu/RVO2/
- LINK
<pre>https://gamma.cs.unc.edu/RVO2/</pre>

#### 论文
- LINK
<pre>https://gamma.cs.unc.edu/ORCA/publications/ORCA.pdf</pre>

#### 参考unity代码
- LINK
<pre>https://github.com/warmtrue/RVO2-Unity</pre>

#### B站参考
- LINK
<pre>https://www.bilibili.com/video/BV1Nb421n7qJ/?spm_id_from=333.999.0.0&amp;vd_source=72868cdf66be986462ce798fe9e21050</pre>
