[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 状态同步

### 参考
- LINK
<pre>https://zhuanlan.zhihu.com/p/555961025</pre>

### AOI与九屏

#### 把地图按照按照大小划分方块区域

#### 每一个区域的大小参考玩家屏幕可视范围，称为一屏

#### 玩家所在屏和向外拓展一屏的范围，称之为9屏

### 场景对象的创建和删除

#### 当客户端的主角进入某个屏

##### 将添加9屏范围内的场景对象

##### 并且通知9屏范围内的其他客户端添加自己

### 主角动作先行

#### 主角做出操作的时候，先本地校验<br/>合法的话先立刻响应，并且发消息通知服务器

#### 如果不合法，就下发一条消息把玩家拉回来，<br/>合法的话就广播给其他的客户端

### 伤害延迟结算

#### 服务器上的事件往往是即时的，比如做伤害技能的时候<br/>飘字的表现是在适合的动作时机，这种情况下伤害数字和死亡结果就<br/>要先暂存起来，等前端动作播完再去检测

### 网络延迟和回滚

#### 技能需要有足够的前摇，尽可能保证在打击帧（前收到服务器的结算数据）

#### 如果偶尔返回消息越过了打击帧，就直接处理伤害数字

### 弹道逻辑

### 服务器补偿

### 玩家行走时，服务器如何同步？

#### 如果是用点击目标的的移动方式

##### 把目标点广播给其他的客户端<br/>其他的客户端进行寻路表现就行

#### 如果是摇杆移动的

##### 每次移动一小点都发送给服务端的话，会台频繁<br/>可以在检测到移动后，隔一定的时间间隔发送给后端<br/>移动后的点

#### 如果没有寻路或者寻路太耗性能，可以用插值的方式去做

### 位置同步之移动预测
- LINK
<pre>https://baddogzz.github.io/2020/01/07/Move-Predict/</pre>
