[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## GPA

### Graphics Frame Analyzer
- LINK
<pre>https://www.intel.com/content/www/us/en/docs/gpa/user-guide/2023-3/graphics-frame-analyzer-window-profiling-view.html</pre>

#### API Log

##### 相当于RenderDockd的Event Browser

##### 选中某个API可以看到这个API相关的Resourcess

##### Resource窗口

###### 分为三大部分

####### Input

######## 输入

######## CBV

######### ConstantBufferViewer

######## IBV

######### Index Buffer Viewer

######## VBV

######### Vertext Buffer Viewer

########## 这里可以看到顶点颜色，UV等

######## Geometry

######### 原始Mesh，导出的是还没经过变换的obj模型文件

####### Execution

######## Arguments

######### 看到的是调用API的参数

######## SH

######### Shader的缩写？

######### 选中SH能看到Shader代码

########## HLSL

########### 好像就只看到VS输入输出？ 没PS相关的代码？

########## DXBC

########### DirectX ByteCode

######## State

######### Depth ,Stencil Blending等状态

####### Output

######## Geometry

######### 这里是经过变换的网格，好像都压扁到一个平面的

######## RTV

######### 这里看到的是一张彩色图，是RenderTextureViewer 的缩写？

######## DSV

######### 是Depth Sampler Viewer？

### 官方文档
- LINK
<pre>https://www.intel.com/content/www/us/en/docs/gpa/user-guide/2023-3/overview.html</pre>
