[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# The Root Topic
> mmd.emoticon=`tree`


## 分离轴定理的含义

### SAT Separating Axis Theorem：如果两个凸多边形不相交<br/>那可能能找到一条直线能完全分开两个图形

### 我们需要测试每条变的方向上释放存在这样的分离轴<br/>如果所有的轴都不能将两个矩形分开，则相交

## 凸多边形
> leftSide=`true`


### 直线穿过图形，如果只有两个相交点，那就是凸多边形

## 投影
> leftSide=`true`

